# Book settings
title: Laboratorio Integrado
author: Juan Marcos Marín / Universidad de Antioquia
logo: content\local\imgs\facultad-exactas+(1).png

repository:
   url: 
   branch: master

launch_buttons:
  binderhub_url: ""
  colab_url: https://colab.research.google.com

html:
  google_analytics_id: 

execute:
  execute_notebooks         : off

